import {createConstants} from '../utils';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REFRESH = 'LOGIN_USER_REFRESH';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_REINIT_TEACHERS = 'REGISTER_REINIT_TEACHERS';

export const REGISTER_LOAD_SCHOOLS_REQUEST = 'REGISTER_LOAD_SCHOOLS_REQUEST';
export const REGISTER_LOAD_SCHOOLS_SUCCESS = 'REGISTER_LOAD_SCHOOLS_SUCCESS';
export const REGISTER_LOAD_SCHOOLS_FAILURE = 'REGISTER_LOAD_SCHOOLS_FAILURE';

export const REGISTER_LOAD_TEACHERS_REQUEST = 'REGISTER_LOAD_TEACHERS_REQUEST';
export const REGISTER_LOAD_TEACHERS_SUCCESS = 'REGISTER_LOAD_TEACHERS_SUCCESS';
export const REGISTER_LOAD_TEACHERS_FAILURE = 'REGISTER_LOAD_TEACHERS_FAILURE';

export const REGISTER_SAVE_USER_REQUEST = 'REGISTER_SAVE_USER_REQUEST';
export const REGISTER_SAVE_USER_SUCCESS = 'REGISTER_SAVE_USER_SUCCESS';
export const REGISTER_SAVE_USER_FAILURE = 'REGISTER_SAVE_USER_FAILURE';
